# Define Trail Options (14 total options)
trails = [
    ["Fort ahead!", "You have arrived at a Fort. Collect 1 supply.", "supplies", None, False],
    ["Town ahead!", "You have arrived at a Town. Remove 1 Calamity.", "calamity", None, False],
    ["Calm road to the left.", "As you were.", "pass", None, False],
    ["Calm road to the right.", "No trouble here, partner.", "pass", None, False],
    ["Calm road straight ahead.", "Remain calm. Carry on.", "pass", None, False],
    ["Treacherous road to the right.", "Receive one calamity.", None, None, True],
    ["Treacherous road to the left.", "Receive one calamity.", None, None, True],
    ["Treacherous road straight ahead.", "Receive one calamity.", None, None, True],
    ["Winding road straight ahead.", "Receive one calamity.", None, None, True],
    ["Road crosses a river to the left.", "Roll and Even Number to Ford the River. Roll a 1 and die by drowning. Roll a 3 or 5 and play passes to the next player.", None, 'even', False],
    ["Road crosses a river to the right.", "Roll and Even Number to Ford the River. Roll an ODD number and lose a supply.", None, 'odd', False],
    ["Winding road crosses a river straight ahead.", "Roll and Even Number to Ford the River. Roll a 1 and die by drowning. Roll a 3 or 5 and play passes to the next player.", None, 'even', False],
    ["Treacherous road crosses a river straight ahead.", "Roll and Even Number to Ford the River. Roll a 1 and die by drowning. Roll a 3 or 5 and play passes to the next player.", None, 'even', False],
    ["Treacherous road crosses a river to the left.", "Roll and Even Number to Ford the River. Roll an ODD number and lose a supply.", None, 'odd', False],
    ["Treacherous road crosses a river to the right.", "Roll and Even Number to Ford the River. Roll an ODD number and lose a supply.", None, 'odd', False],
    ]

# Define Supply Options (10 total options)
supplies = [
    "Half a Pizza",
    "Bullets for your 9",
    "Vicodin",
    "A keg of Beer",
    "A Lady's dress",
    "Spare Parts",
    "Two Oxen",
    "A Dream Catcher",
    "A Mace",
    "A partially eaten birthday cake",
    "Soylent",
]

# Define Calamities (15 total options)
Calamities = {
    "Kenny": "Kenny killed you.",
    "Dino": "Dino ate all your pizza and beer. You'll need a Mace to kill him and eat him or you'll die.",
    "Eating Disorder": "You've developed an eating disorder. You'll need a partially eaten birthday cake, half a pizza and some Soylent to survive.",
    "Soylent": "Rejoice! You have found some extra Soylent.",
    "Fractal Snake": "You were bitten by a Fractal Snake. You'll need bullets for your 9 to kill it before it kills you.",
    "Treason": "You're being accused of Treason. You'll need to ward off this bad luck with a dream catcher or you'll die.",
    "Extreme Cold": "Beat the cold by drinking as much beer as you can. You'll need a keg or you'll die.",
    "Misbehaving Oxen": "Your Oxen were misbehaving, so another member killed them. You'll need 2 more Oxen or everyone dies.",
    "Measles": "You have the Measles. Lose a turn unless you have some Vicodin to keep going.",
    "Dysentery": "You died of Dysentery.",
    "Flat Tire": "Your steam mobile has a flat tire. You'll need spare parts to fix it or everyone dies.",
    "Out of Steam": "Your steam mobile ran out of steam. You'll need to have 2 Oxen to pull it or everyone dies.",
    "Terminator": "Terminator showed up from the future to kill you. You need to disguise yourself with a new dress or he kills you.",
    "God": "God killed you. You're dead.",
    "Satan": "Satan has decided to give you one last chance. Sit out for 2 rounds. The group cannot use your supplies.",
    "Peyote Trip": "You ate some random Peyote that you found along the way. You'll need half a pizza to get over this or you'll die.",
}

# Define paths to ascii picture files
ascii = {
    "trail" : "ascii_pics/trail_pic",
    "9mm" : "ascii_pics/9mm",
    "beer" : "ascii_pics/beer",
    "cactus" : "ascii_pics/cactus",
    "cake" : "ascii_pics/cake",
    "cholera" : "ascii_pics/cholera",
    "clothes" : "ascii_pics/clothes",
    "dead_oxen" : "ascii_pics/dead_oxen",
    "death" : "ascii_pics/death",
    "dice" : "ascii_pics/dice",
    "dino" : "ascii_pics/dino",
    "disentary" : "ascii_pics/disentary",
    "disorder" : "ascii_pics/disorder",
    "donQ" : "ascii_pics/donQ",
    "dream_catcher" : "ascii_pics/dream_catcher",
    "enterprise" : "ascii_pics/enterprise",
    "extreme_cold" : "ascii_pics/extreme_cold",
    "fort" : "ascii_pics/fort",
    "fractal_snake" : "ascii_pics/fractal_snake",
    "god" : "ascii_pics/god",
    "kenny" : "ascii_pics/kenny",
    "knight" : "ascii_pics/knight",
    "mace" : "ascii_pics/mace",
    "mountains" : "ascii_pics/mountains",
    "mushroom_cloud" : "ascii_pics/mushroom_cloud",
    "oxen" : "ascii_pics/oxen",
    "pizza" : "ascii_pics/pizza",
    "rain" : "ascii_pics/rain",
    "repair" : "ascii_pics/repair",
    "snake" : "ascii_pics/snake",
    "spare_parts" : "ascii_pics/spare_parts",
    "steam_wagon" : "ascii_pics/steam_wagon",
    "terminator" : "ascii_pics/terminator",
    "tornado" : "ascii_pics/tornado",
    "treason" : "ascii_pics/treason",
    "vicodin" : "ascii_pics/vicodin",
}
